---
  - name: allbus | install_postgis.yml | install postgis dependencies
    apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
    with_items:
      - "binutils"
      - "libproj-dev"
      - "gdal-bin"
    environment: env

  - name: allbus | install_postgis.yml | install postgis
    apt: name={{ item }} state=present update_cache=yes cache_valid_time=3600
    with_items:
      - "postgresql-9.4-postgis-2.1"
    environment: env
